### PR TITLE
Added slate (pretty) documentation

### PR DESCRIPTION
**Pull request by g33kcentric**

### CODE REVIEW

**Comment by Floppy** [comment]
@g33kcentric this is really great, thanks for doing it! I've not come across Slate before, I assume it's generated from the openapi definition?

**Comment by Floppy** [comment]
I'll check with the rest of the team, but we should definitely use this as the primary documentation. It's lovely :)

**Comment by Floppy** [comment]
RIght, I've caught up with Basecamp now, sorry, I got a bit out of sync and hadn't seen your name before! Ignore all my confusion, I'll swap github pages over to point at /docs instead of /.

**Comment by g33kcentric** [comment]
Cool, no problem :) Someone may want to update the logo on the docs :)

**Pull request merged**
